import os
import json
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure OpenAI client for OpenRouter
client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=os.getenv("OPENROUTER_API_KEY"),
)

def classify_attack(alert):
    """
    Uses API to classify a Wazuh alert.
    Returns a JSON string containing the attack type, analysis, severity, and remediation steps.
    """
    description = alert.get('rule', {}).get('description', '')
    agent_name = alert.get('agent', {}).get('name', 'Unknown')
    rule_level = alert.get('rule', {}).get('level', 'Unknown')

    # Basic fallback if no description is provided
    if not description:
        return json.dumps({
            "attack_type": "Unknown",
            "analysis": "No alert description provided by Wazuh.",
            "severity": "Low",
            "remediation": "N/A"
        })

    prompt = f"""
    You are an expert Security Operations Center (SOC) Analyst.
    Analyze the following security event alert generated by Wazuh:
    
    Alert Description: {description}
    Agent Name: {agent_name}
    Rule Level: {rule_level}

    Check for "File integrity monitoring" or "syscheck" in the description.
    If it's a FIM alert, identify which file was changed and what was the nature of the change (added, modified, deleted).

    Provide a JSON response with exactly these six keys:
    1. "attack_type": A short classification string (e.g., "File Modification", "Brute Force Attempt", "Persistence").
    2. "mitre_tactic": The corresponding MITRE ATT&CK Tactic (e.g., "Defense Evasion", "Persistence", "Credential Access").
    3. "mitre_technique": The specific MITRE Technique with ID (e.g., "Indicator Removal (T1070)", "Data Manipulation (T1565)").
    4. "analysis": A 1-2 sentence explanation of what this event implies (mention specific files if available).
    5. "severity": "Critical", "High", "Medium", or "Low".
    6. "remediation": 1-2 actionable steps (e.g., "Verify file hash", "Revert file change").
    """

    try:
        response = client.chat.completions.create(
            model="openai/gpt-4o-mini",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.1
        )
        
        result_text = response.choices[0].message.content
        
        if result_text.startswith("```json"):
            result_text = result_text.replace("```json", "").replace("```", "").strip()
        elif result_text.startswith("```"):
            result_text = result_text.replace("```", "").strip()

        try:
            result = json.loads(result_text)
            return json.dumps(result)
        except json.JSONDecodeError as decode_error:
            print(f"JSON Parsing Error. Raw AI Response:\n{result_text}")
            raise decode_error

    except Exception as e:
        print(f"OpenRouter API Error: {e}")
        
        is_rate_limit = "429" in str(e) or "Quota exceeded" in str(e) or "rate" in str(e).lower()
        
        desc_lower = description.lower()
        mitre_tactic = "Defense Evasion"
        mitre_technique = "Indicator Removal (T1070)"
        attack_type = "Security Event"
        
        # FIM Check
        if "file integrity monitoring" in desc_lower or "syscheck" in desc_lower:
            attack_type = "File Integrity Change"
            mitre_tactic = "Defense Evasion"
            mitre_technique = "Indicator Removal on Host (T1070)"
            remediation = "Verify if this file change was authorized. If not, restore from backup."
        elif "logon failure" in desc_lower or "authentication failure" in desc_lower:
            attack_type = "Brute Force Attempt"
            mitre_tactic = "Credential Access"
            mitre_technique = "Brute Force (T1110)"
            remediation = "Disable the source IP and enforce multi-factor authentication."
        elif "special privileges" in desc_lower:
            attack_type = "Privilege Escalation"
            mitre_tactic = "Privilege Escalation"
            mitre_technique = "Exploitation for Privilege Escalation (T1068)"
            remediation = "Patch the target vulnerability and audit system logs."
        else:
            attack_type = "General Security Event"
            mitre_tactic = "Execution"
            mitre_technique = "User Execution (T1204)"
            remediation = "Investigate manually for unusual system activity."

        analysis_msg = (
            "⚠️ AI Analysis temporarily unavailable (API Quota Exceeded). FIM detection active."
            if is_rate_limit 
            else f"Fallback classification used because AI generation failed."
        )

        return json.dumps({
            "attack_type": attack_type,
            "mitre_tactic": mitre_tactic,
            "mitre_technique": mitre_technique,
            "analysis": analysis_msg,
            "severity": "Medium",
            "remediation": remediation
        })
