import os
import json
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure OpenAI client for OpenRouter
client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=os.getenv("OPENROUTER_API_KEY"),
)

# ========================================================================
# Organization Security Controls (Hardcoded for Infrastructure Context)
# ========================================================================
ORG_SECURITY_CONTROLS = """
The following existing security controls are deployed in the organization's infrastructure.
You MUST factor these into your risk assessment to determine the ACTUAL organizational risk:

1. Servers are NOT exposed to the internet and are accessible ONLY within the internal network (no external SSH access, even with valid credentials).
2. A perimeter Palo Alto Networks firewall is in place with Threat Prevention and Anti-Spyware profiles enabled.
3. Wazuh agents are deployed on ALL servers for real-time log monitoring, including command execution tracking and alerting on suspicious activities.
4. End users do NOT have administrative/root privileges, and data exfiltration outside the internal network is restricted.
5. The organization manages 180+ assets monitored by these controls.
"""

def classify_attack(alert):
    """
    Uses API to classify a Wazuh alert with context-aware organizational risk assessment.
    Returns a JSON string containing the attack type, analysis, severity, remediation,
    CVE/CWE, CVSS score, base severity, org risk severity, and org risk assessment.
    """
    description = alert.get('rule', {}).get('description', '')
    agent_name = alert.get('agent', {}).get('name', 'Unknown')
    rule_level = alert.get('rule', {}).get('level', 'Unknown')
    rule_groups = alert.get('rule', {}).get('groups', [])
    full_log = alert.get('full_log', '')

    # Basic fallback if no description is provided
    if not description:
        return json.dumps({
            "attack_type": "Unknown",
            "analysis": "No alert description provided by Wazuh.",
            "severity": "Low",
            "remediation": "N/A",
            "mitre_tactic": "N/A",
            "mitre_technique": "N/A",
            "cve_cwe": "N/A",
            "cvss_score": "N/A",
            "base_severity": "Low",
            "org_risk_severity": "Low",
            "org_risk_assessment": "No data available for assessment."
        })

    prompt = f"""
    You are an expert Security Operations Center (SOC) Analyst and Information Security Risk Assessor.
    Analyze the following security event alert generated by Wazuh:
    
    Alert Description: {description}
    Agent Name: {agent_name}
    Rule Level: {rule_level}
    Rule Groups: {', '.join(rule_groups) if rule_groups else 'N/A'}
    Full Log Snippet: {full_log[:500] if full_log else 'N/A'}

    {ORG_SECURITY_CONTROLS}

    Check for "File integrity monitoring" or "syscheck" in the description.
    If it's a FIM alert, identify which file was changed and what was the nature of the change (added, modified, deleted).

    Provide a JSON response with exactly these THIRTEEN keys:

    1. "threat_actor": "Classification of the actor (e.g., 'Advanced Persistent Threat', 'Botnet', 'Cyber Criminal'). NEVER use 'Unknown'.",
    2. "attack_vector": "Technical method (e.g., 'SMB Buffer Overflow', 'JNDI Remote Code Execution'). NEVER use 'Unknown'.",
    3. "mitre_technique_id": "MITRE ID (e.g., T1059).",
    4. "mitre_technique_name": "Full name.",
    5. "cve_id": "Comma-separated list of REAL CVE IDs (e.g., 'CVE-2021-44228, CVE-2021-45046') or 'N/A'.",
    6. "cwe_id": "Comma-separated list of CWE IDs (e.g., 'CWE-78, CWE-77').",
    7. "cvss_score": "Standard CVSS (0.0-10.0).",
    8. "cwss_score": "Environmental Score (0.0-100.0).",
    9. "risk_severity": "Critical/High/Medium/Low.",
    10. "remediation_steps": "Action-oriented steps. ULTRA-CONCISE (max 5 words per step). USE NEWLINES (\\n) between steps.",
    11. "forensic_summary": "One-line technical summary.",
    12. "org_impact": "Impact on the specific asset.",
    13. "reasoning": "Internal logic for this classification."

    STRICT POLICY: 
    - NO 'Unknown', NO 'N/A', NO placeholders. 
    - If data is sparse, use HEURISTIC REASONING to provide the most likely IDs and scores. 
    - This is for a high-fidelity security research project; 100% data population is MANDATORY.
    """

    try:
        response = client.chat.completions.create(
            model="google/gemini-2.0-flash-001",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.1,
            max_tokens=600,
            response_format={ "type": "json_object" }
        )
        
        result_text = response.choices[0].message.content
        
        if result_text.startswith("```json"):
            result_text = result_text.replace("```json", "").replace("```", "").strip()
        elif result_text.startswith("```"):
            result_text = result_text.replace("```", "").strip()

        try:
            result = json.loads(result_text)
            # Ensure all required keys exist
            required_keys = ["attack_type", "mitre_tactic", "mitre_technique", "analysis",
                           "severity", "remediation", "cve_cwe", "cvss_score", "cwss_score",
                           "base_severity", "org_risk_assessment"]
            for key in required_keys:
                if key not in result:
                    result[key] = "N/A"
            
            # --- SEVERITY SAFETY OVERRIDE & CVSS SYNC ---
            desc_lower = description.lower()
            atk_lower = str(result.get("attack_type", "")).lower()
            
            # 1. Check for Critical Threats
            if any(x in desc_lower or x in atk_lower for x in ["wannacry", "ransomware", "encrypt", "malware"]):
                result["severity"] = "Critical"
                result["org_risk_severity"] = "Critical"
                result["cvss_score"] = "9.8" # Sync with Critical Range (9.0-10.0)
                result["org_risk_assessment"] = "CRITICAL OVERRIDE: " + str(result.get("org_risk_assessment", ""))
            
            # 2. Check for Admin/Root activity (High Priority)
            elif any(x in desc_lower or x in atk_lower for x in ["root", "privilege escalation", "admin"]):
                if result.get("severity") not in ["Critical", "High"]:
                    result["severity"] = "High"
                    result["org_risk_severity"] = "High"
                    result["cvss_score"] = "7.5" # Sync with High Range (7.0-8.9)
            
            # 3. Final Range Validation (Ensure CVSS matches the final Severity string)
            final_sev = result.get("severity", "Low")
            try:
                current_cvss = float(result.get("cvss_score", 0))
            except:
                current_cvss = 0

            if final_sev == "Critical":
                if current_cvss < 9.0: result["cvss_score"] = "9.5"
                try:
                    if float(result.get("cwss_score", 0)) < 90.0: result["cwss_score"] = "95.0"
                except: result["cwss_score"] = "95.0"
            elif final_sev == "High":
                if current_cvss < 7.0 or current_cvss >= 9.0: result["cvss_score"] = "8.2"
                try:
                    val = float(result.get("cwss_score", 0))
                    if val < 70.0 or val >= 90.0: result["cwss_score"] = "82.5"
                except: result["cwss_score"] = "82.5"
            elif final_sev == "Medium":
                if current_cvss < 4.0 or current_cvss >= 7.0: result["cvss_score"] = "5.5"
                try:
                    val = float(result.get("cwss_score", 0))
                    if val < 40.0 or val >= 70.0: result["cwss_score"] = "58.0"
                except: result["cwss_score"] = "58.0"
            elif final_sev == "Low":
                if current_cvss < 0.1 or current_cvss >= 4.0: result["cvss_score"] = "3.2"
                try:
                    val = float(result.get("cwss_score", 0))
                    if val < 10.0 or val >= 40.0: result["cwss_score"] = "25.0"
                except: result["cwss_score"] = "25.0"
            elif final_sev == "None":
                result["cvss_score"] = "0.0"
                result["cwss_score"] = "5.0"

            result["org_risk_severity"] = result.get("severity", "Unknown")

            return json.dumps(result)
        except json.JSONDecodeError as decode_error:
            print(f"JSON Parsing Error. Raw AI Response:\n{result_text}")
            raise decode_error

    except Exception as e:
        print(f"OpenRouter API Error: {e}")
        
        is_rate_limit = "429" in str(e) or "Quota exceeded" in str(e) or "rate" in str(e).lower()
        
        desc_lower = description.lower()
        mitre_tactic = "Defense Evasion"
        mitre_technique = "Indicator Removal (T1070)"
        attack_type = "Security Event"
        cve_cwe = "N/A"
        cvss_score = "N/A"
        cwss_score = "0.0"
        base_severity = "Medium"
        org_risk_severity = "Low"
        org_risk_assessment = "AI analysis unavailable. Based on organizational security controls (internal network only, Palo Alto firewall, Wazuh monitoring, no root access), the risk is assessed as reduced. Manual investigation recommended."
        
        # FIM Check
        if "file integrity monitoring" in desc_lower or "syscheck" in desc_lower:
            attack_type = "File Integrity Change"
            mitre_tactic = "Defense Evasion"
            mitre_technique = "Indicator Removal on Host (T1070)"
            cve_cwe = "CWE-73" # External Control of File Name or Path
            base_severity = "High"
            org_risk_severity = "Medium"
            remediation = "Verify if this file change was authorized. If not, restore from backup."
            org_risk_assessment = "File integrity change detected. While Wazuh agents provide real-time monitoring and the internal network restricts external access, unauthorized file modifications could indicate insider threat activity. Remediation priority: Medium - verify change authorization within 24 hours."
        elif "logon failure" in desc_lower or "authentication failure" in desc_lower:
            attack_type = "Brute Force Attempt"
            mitre_tactic = "Credential Access"
            mitre_technique = "Brute Force (T1110)"
            cve_cwe = "CWE-307" # Improper Restriction of Excessive Authentication Attempts
            base_severity = "High"
            org_risk_severity = "Low"
            remediation = "Disable the source IP and enforce multi-factor authentication."
            org_risk_assessment = "Brute force attempt detected. Given that servers are internal-only with no external SSH access, external exploitation is not feasible. The Palo Alto firewall with Threat Prevention further mitigates this risk. However, this could indicate an insider threat or compromised internal device. Remediation priority: Low - monitor for repeated attempts from same source."
        elif "wannacry" in desc_lower or "ransomware" in desc_lower or "malware" in desc_lower:
            attack_type = "Malware Infection"
            mitre_tactic = "Impact"
            mitre_technique = "Data Encrypted for Impact (T1486)"
            cve_cwe = "CVE-2017-0144" # EternalBlue
            base_severity = "Critical"
            org_risk_severity = "Critical"
            remediation = "Isolate infected host immediately. Shutdown SMB services. Restore from offline backups."
            org_risk_assessment = "CRITICAL: Ransomware indicators detected. Although the network is internal, ransomware like WannaCry spreads laterally via SMB. Our internal isolation won't stop a worm once it's inside. Immediate isolation required to prevent total infrastructure loss."
        elif "xss" in desc_lower or "cross-site scripting" in desc_lower:
            attack_type = "Cross-Site Scripting (XSS)"
            mitre_tactic = "Initial Access"
            mitre_technique = "Exploit Public-Facing Application (T1190)"
            cve_cwe = "CWE-79" # Cross-site Scripting
            base_severity = "High"
            org_risk_severity = "Low"
            remediation = "Sanitize user input and implement Content Security Policy (CSP)."
            org_risk_assessment = "XSS attempt detected in HTTP request. Perimeter Palo Alto firewall with Threat Prevention and internal-only access significantly reduce the likelihood of a successful exploit reaching a vulnerable endpoint. Remediation priority: Low."
        elif "special privileges" in desc_lower or "root" in desc_lower:
            attack_type = "Privilege Escalation"
            mitre_tactic = "Privilege Escalation"
            mitre_technique = "Exploitation for Privilege Escalation (T1068)"
            cve_cwe = "CWE-269" # Improper Privilege Management
            base_severity = "Critical"
            org_risk_severity = "Critical"
            remediation = "Patch the target vulnerability and audit system logs. Terminate the suspicious session."
            org_risk_assessment = "CRITICAL: Privilege escalation attempt to root/admin. This bypasses our 'Restricted Privileges' control. Since the attacker is already internal, this is a direct threat to the core infrastructure. Immediate investigation required."
        else:
            attack_type = "General Security Event"
            mitre_tactic = "Execution"
            mitre_technique = "User Execution (T1204)"
            cve_cwe = "CWE-20" # Improper Input Validation
            base_severity = "Medium"
            org_risk_severity = "Medium"
            remediation = "Investigate manually for unusual system activity."
            org_risk_assessment = "Security event detected. While we have multiple layers of defense, the nature of this event requires manual review to ensure internal integrity is not compromised."

        analysis_msg = (
            "⚠️ AI Analysis temporarily unavailable (API Quota Exceeded). Fallback risk assessment active using organizational security controls."
            if is_rate_limit 
            else f"Fallback classification used because AI generation failed. Organizational controls factored into risk assessment."
        )

        return json.dumps({
            "attack_type": attack_type,
            "mitre_tactic": mitre_tactic,
            "mitre_technique": mitre_technique,
            "analysis": analysis_msg,
            "severity": org_risk_severity,
            "remediation": remediation,
            "cve_cwe": cve_cwe,
            "cvss_score": cvss_score,
            "cwss_score": cwss_score,
            "base_severity": base_severity,
            "org_risk_severity": org_risk_severity,
            "org_risk_assessment": org_risk_assessment
        })
